"""Update upload model

Revision ID: 266f193ea6e9
Revises: 10dd4ec6da14
Create Date: 2026-07-29 22:06:11.966041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266f193ea6e9'
down_revision: Union[str, Sequence[str], None] = '10dd4ec6da14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('uploads', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('uploads', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('uploads', 'contributor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('uploads', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('uploads', 'contributor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('uploads', 'created_at')
    op.drop_column('uploads', 'stored_filename')
    op.drop_column('uploads', 'original_filename')
    # ### end Alembic commands ###
